ktor:
  application:
    modules:
      - com.example.ApplicationKt.module
  deployment:
    port: 80

postgres:
  address: '$POSTGRES_ADDRESS:5432'
  database: '$POSTGRES_DB'
  user: '$POSTGRES_USER'
  password: '$POSTGRES_PASSWORD'

